[package]
name = "rust"
version = "0.1.0"
authors = ["Justin Kasteleijn"]
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
